[project]
name = "amaranth-stream"
version = "0.1.0"
description = "Stream processing library for Amaranth HDL"
requires-python = ">=3.9"
dependencies = ["amaranth>=0.5.10"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
